version: "3" 
services:
  rundeck:
    build: . 
    volumes:
      - ./etc/rundeck:/etc/rundeck
      - ./var/rundeck:/var/rundeck
      - ./var/lib/rundeck/.ssh:/var/lib/rundeck/.ssh
      - ./var/lib/rundeck/logs:/var/lib/rundeck/logs
      - ./var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage
      - ./var/lib/mysql:/var/lib/mysql
      - ./var/log/rundeck:/var/log/rundeck
      - ./opt/rundeck-plugins:/opt/rundeck-plugins 
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      RDECK_JVM: -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Tokyo
      RUNDECK_WITH_SSL: "true"
    ports:
      - 4443:4443
    networks:
      - webnet
networks:
  webnet:
